Added Getpartylist in register
Altinn/altinn-register pull request #100
Opened 2023-01-15 19:25 UTC by acn-dgopa

Added endpoint for retreiving partylist for a list of partyids

## Description

## Related Issue(s)
- #{issue number}

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

2023-01-16 10:48 UTC, SandGrainOne requested changes
A few things I would like to have changed

2023-01-16 10:48 UTC, SandGrainOne commented on src/Controllers/PartiesController.cs
> +            try
Remove the try-catch. The middleware will produce a response with status code 500 if there is an exception. A test shold be able to verify this.

2023-01-16 10:48 UTC, SandGrainOne commented on src/Services/Implementation/PartiesWrapper.cs
> +    [ExcludeFromCodeCoverage]
It's possible to create tests by mocking a HttpMessageHandler. We have examples of this in Profile. Look for [DelegatingHandlerStub](https://github.com/Altinn/altinn-profile/blob/42308b53b8e2949d21e5e7e434e03b76a4db31e0/test/Altinn.Profile.Tests/Mocks/DelegatingHandlerStub.cs) and how we use it.

2023-01-16 10:48 UTC, SandGrainOne commented on src/Services/Implementation/PartiesWrapper.cs
> +            try
Remove the try catch. The middleware should handle the exception logging.

2023-01-19 07:46 UTC, SandGrainOne commented on test/Utils/TestDataLoader.cs
> +            string? unitTestFolder = Path.GetDirectoryName(new Uri(typeof(PartiesControllerTests).Assembly.Location).LocalPath);
The questionmark on `string?` is unnecessary.

2023-01-19 07:54 UTC, SandGrainOne commented on test/IntegrationTests/PartiesControllerTests.cs
> +            DelegatingHandlerStub messageHandler = new(async (request, token) =>
Should we consider making an assert ot two on the request being sent to SBL Bridge? Alternatively remove the variable.

2023-01-19 10:09 UTC, SandGrainOne commented on test/IntegrationTests/PartiesControllerTests.cs
> +            Assert.Equal(response.RequestMessage.Content, testRequest.Content);
I don't trust these asserts to actually test anything of value. I suspect that they are comparing one object with itself. In other words, what we have here are two variables/pointers pointing to the same address in memory.

2023-01-23 12:06 UTC, acn-dgopa commented on test/IntegrationTests/PartiesControllerTests.cs
> +            Assert.Equal(response.RequestMessage.Content, testRequest.Content);
i have now udpated the asserts similar to profile component. I hope the udpated asserts makes sense :)

2023-01-23 14:38 UTC, merged