Added two new methods to fetch Party and List<Party> based on uuid
Altinn/altinn-register pull request #161
Opened 2024-01-10 14:29 UTC by lovoll

also fixed the GetParty to fetch PartyUuid by setting option for case insensitive property name as it is defined as PartyUUID in SblBridge and PartyUuid in Altinn.Platform.Models

## Description

## Related Issue(s)
- #{issue number}

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

2024-01-16 14:44 UTC, SandGrainOne requested changes

2024-01-17 07:46 UTC, lovoll commented on src/Controllers/PartiesController.cs
> +                return NotFound();
Fixed

2024-01-17 07:46 UTC, lovoll commented on src/Controllers/PartiesController.cs
> +            parties = await _partiesWrapper.GetPartyListByUuid(partyUuids);
Fixed

2024-01-17 09:47 UTC, SandGrainOne approved these changes

2024-01-17 10:06 UTC, SandGrainOne commented on src/Controllers/PartiesController.cs
> +        public async Task<ActionResult<Party>> GetByUuid(Guid partyUuid)
Consider adding `[Authorize]` and the same validation as in the `Get(int partyId)` method above.

2024-01-17 12:47 UTC, lovoll commented on test/UnitTests/PartyWrapperTest.cs
> +        public async Task GetParty_SblBridge_finds_party_Target_returns_NotFound()
Renamed

2024-01-17 13:49 UTC, lovoll commented on test/UnitTests/PartyWrapperTest.cs
> +        public async Task GetParty_SblBridge_finds_partylist_Target_returns_NotFound()
Renamed

2024-01-17 14:24 UTC, SandGrainOne commented
Looks good!

2024-01-17 16:22 UTC, merged