Add criteria to split name into first, middle, and last.
Altinn/altinn-register pull request #302
Opened 2024-09-16 13:08 UTC by Ahmed-Ghanam

## Description
Extend search criteria to determine if the name should be split into first, middle, and last components. Add properties for first, middle, and last names to the search result.

## Related Issue(s)
- #593

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

2024-09-17 07:02 UTC, Alxandr requested changes

2024-09-17 07:02 UTC, Alxandr commented on src/Altinn.Platform.Models/src/Altinn.Platform.Models/Register/PartyName.cs
> +    public string? FirstName { get; set; }
I think these 3 fields should probably be put inside a sub-object. The reason for that is currently, even when you are including the name components, if for instance middle name is `null`, the field will not be included. But if you put them in a sub-object (`nameComponents` for instance), the whole thing will be `null` or not at once.

2024-09-17 13:20 UTC, Ahmed-Ghanam commented on src/Altinn.Register/src/Altinn.Register/Clients/PartiesClient.cs
> +            _memoryCache.Set(cacheKey, partyName, new TimeSpan(0, _cacheTimeoutForPartyNames, 0));
I have update the cache key so it takes into consideration the component to include.

2024-09-17 13:21 UTC, Ahmed-Ghanam commented on src/Altinn.Platform.Models/src/Altinn.Platform.Models/Register/PartyLookup.cs
> +    public bool SplitPersonName { get; set; } = false;
The following PartyComponentOptions is implemented:
```
/// <summary>
/// Represents options for including different components of a party.
/// </summary>
[Flags]
public enum PartyComponentOptions
{
    /// <summary>
    /// No extra components are included.
    /// </summary>
    None = 0,

    /// <summary>
    /// Include the party's first, middle, and last name.
    /// </summary>
    NameComponents = 1 << 0,
}

```

2024-09-17 13:22 UTC, Ahmed-Ghanam commented on src/Altinn.Platform.Models/src/Altinn.Platform.Models/Register/PartyName.cs
> +    public string? FirstName { get; set; }
These three fields are now wrapped in the new type `PersonNameComponents`

2024-09-17 13:55 UTC, Alxandr commented on src/Altinn.Platform.Models/src/Altinn.Platform.Models/Register/PersonNameComponents.cs
> +    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
These should probably not have `JsonIgnore`

2024-09-17 13:55 UTC, Alxandr commented on src/Altinn.Register/src/Altinn.Register/Clients/PartiesClient.cs
> +        string cacheKey = string.IsNullOrEmpty(partyLookup.Ssn) ? $"n:{lookupValue}" : $"n:{lookupValue}-c:{includeNameComponents}";
Why are you caching results differently based on whether or not you want the name component? That seems like throwing away good data for no apparent reason?

2024-09-17 13:55 UTC, Alxandr commented on src/Altinn.Register/src/Altinn.Register/Clients/PartiesClient.cs
> +        bool includeNameComponents = !string.IsNullOrEmpty(partyLookup.Ssn) && partyLookup.IncludeComponents == PartyComponentOptions.NameComponents;
Don't use equality checks with flags enums like this, instead use `HasFlags`. Also, you don't need to care if `Ssn` is set.

2024-09-17 13:55 UTC, Alxandr commented on src/Altinn.Platform.Models/src/Altinn.Platform.Models/Register/PersonNameComponents.cs
> +public record PersonNameComponents
Seeing as this is a new record, probably just make it immutable by replacing all of the `set;` with `init;`.

2024-09-17 13:57 UTC, Alxandr commented on src/Altinn.Register/test/Altinn.Register.Tests/IntegrationTests/PartiesControllerTests.cs
> +    public static TheoryData<PartyLookup> GetPartyLookupTestData()
Xunit prefers theory data being (xunit)-serializable. It would be better to make this a `TheoryData<string, PartyComponentOptions>`, then build the actual `PartyLookup` in the test method.

2024-09-18 06:14 UTC, Ahmed-Ghanam commented on src/Altinn.Platform.Models/src/Altinn.Platform.Models/Register/PersonNameComponents.cs
> +    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
Keeping the `JsonIgnore` attribute on the properties within `PersonNameComponents` ensures consistent behavior across different contexts where `PersonNameComponents` might be used.

2024-09-18 08:50 UTC, Alxandr commented on src/Altinn.Register/test/Altinn.Register.Tests/IntegrationTests/PartiesControllerTests.cs
> +        PartyNamesLookupResult actualResult = JsonSerializer.Deserialize<PartyNamesLookupResult>(responseContent, options);
You're deserializing the same content twice? Why? And what makes one of these "from cache", when it's the same content?

2024-09-18 08:50 UTC, Alxandr commented on src/Altinn.Platform.Models/src/Altinn.Platform.Models/Register/PartyLookup.cs
> +    public PartyComponentOptions IncludeComponents { get; set; } = PartyComponentOptions.None;
This almost definitely does not belong in `PartyLookup` - rather, it should probably be a query parameter on the controller-action instead

2024-09-18 08:50 UTC, Alxandr commented on src/Altinn.Platform.Models/src/Altinn.Platform.Models/Register/PartyName.cs
> +    public PersonNameComponents? PersonNameComponents { get; set; }
Just calling the property `personName` is probably good enough.

2024-09-18 08:50 UTC, Alxandr commented on src/Altinn.Platform.Models/src/Altinn.Platform.Models/Register/PersonNameComponents.cs
> +    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
And how exactly does it do that?

2024-09-18 12:45 UTC, Alxandr commented on src/Altinn.Register/test/Altinn.Register.Tests/IntegrationTests/PartiesControllerTests.cs
> +    public async Task PostPartyNamesLookup_ValidInput_NameComponents_OK(string[] socialSecurityNumber, PartyComponentOptions nameComponent)
Given that this is really testing a HTTP endpoint, rather than having a `PartyComponentOptions` as a input, it would make more sense to take in a query string value. There are 3 different values that should be tested:

* `` (empty string)
* `?includeComponents=` (empty parameter)
* `?includeComponents=person-name`

If you need help with the implementation, the resource registry has a model binder for a similar enum:

* [Model binder](https://github.com/Altinn/altinn-resource-registry/blob/290e0c3af880f5c0a501b196c5fa31498ec220c0/src/Altinn.ResourceRegistry/Models/ModelBinding/AccessListIncludesModelBinder.cs#L14)
* [Swashbuckle schema filter](https://github.com/Altinn/altinn-resource-registry/blob/290e0c3af880f5c0a501b196c5fa31498ec220c0/src/Altinn.ResourceRegistry/Models/ApiDescriptions/AccessListIncludesSchemaFilter.cs#L14)

2024-09-19 08:58 UTC, Ahmed-Ghanam commented on src/Altinn.Register/test/Altinn.Register.Tests/IntegrationTests/PartiesControllerTests.cs
> +        PartyNamesLookupResult actualResult = JsonSerializer.Deserialize<PartyNamesLookupResult>(responseContent, options);
This was code I copied from a similar test unit. I removed it because we do not test caching.

2024-09-19 08:58 UTC, Ahmed-Ghanam commented on src/Altinn.Register/test/Altinn.Register.Tests/IntegrationTests/PartiesControllerTests.cs
> +    public async Task PostPartyNamesLookup_ValidInput_NameComponents_OK(string[] socialSecurityNumber, PartyComponentOptions nameComponent)
I modified the unit test to test the result using valid inputs

2024-09-19 12:31 UTC, Alxandr commented on src/Altinn.Register/test/Altinn.Register.Tests/IntegrationTests/PartiesControllerTests.cs
> +            { ["01039012345","01017512345"], "?includeComponents=0" },
These are horrible API options. We should not make an API that requires sending arbitrary numbers that have no apparently semantic meaning.

2024-09-19 12:41 UTC, Ahmed-Ghanam commented on src/Altinn.Register/test/Altinn.Register.Tests/IntegrationTests/PartiesControllerTests.cs
> +            { ["01039012345","01017512345"], "?includeComponents=0" },
These are test data intended for building queries. If you have an example of well-structured/not-horrible test data, it would be greatly appreciated.

2024-09-20 06:57 UTC, Alxandr commented on src/Altinn.Register/test/Altinn.Register.Tests/IntegrationTests/PartiesControllerTests.cs
> +            { ["01039012345","01017512345"], "?includeComponents=0" },
This is a flags enum. You can't just expect the values to be used as strings. I already explained what I expect to work, but to expand on it further:

* (empty string, no query): `PartyComponentOptions.None`
* `?includeComponents=` (that is, the query value is an empty string/null): `PartyComponentOptions.None`
* `?includeComponents=person-name`: `PartyComponentOrder.NameComponents`
* `?includeComponents=none`: bad request
* `?includeComponents=anything-else-really`: bad request

I care much more that the HTTP API is well designed than how it's actually implemented - cause the implementation can always be changed later. But the API is basically locked once it's merged.

2024-09-20 13:34 UTC, SandGrainOne reviewed
Some findings from me.

2024-09-20 13:34 UTC, SandGrainOne commented on src/Altinn.Register/test/Altinn.Register.Tests/IntegrationTests/PartiesControllerTests.cs
> +            return Task.FromResult(new HttpResponseMessage(HttpStatusCode.BadRequest));
This message handler is for simulating the response from SBLBridge. In this test the the call chain should never get that far. The invalid input is detected long before a call to SBLBridge is being made. 

If we want to verify this properly we should avoid returning BadRequest here as that could confuse the intention of the test. Especially the comment. Could we return something else or maybe throw an exception instead? Remove the comment.

Another options could be to simply just not provide a message handler.

2024-09-23 06:15 UTC, Ahmed-Ghanam commented on src/Altinn.Register/src/Altinn.Register/Clients/PartiesClient.cs
> +            _memoryCache.Set(cacheKey, partyName, new TimeSpan(0, _cacheTimeoutForPartyNames, 0));
We have already fixed this issue. Here’s how it works now:
Data Retrieval: When we need information about a person, we get all their data from our source, including their name components.
Caching: We save (cache) all this data so we don’t have to fetch it again.
On-Demand Name Retrieval: If someone asks for the name parts later, we simply pull them from the cached data.
This way, we always have the name parts ready to return without needing to fetch the data again.

2024-09-23 06:22 UTC, Ahmed-Ghanam commented on src/Altinn.Register/test/Altinn.Register.Tests/IntegrationTests/PartiesControllerTests.cs
> +                "?includeComponents=nameComponents" => testPartyNames.Where(e => socialSecurityNumbers.Contains(e.Ssn))
@Alxandr recommends utilizing an enum parser to circumvent the direct use of enum member values and names. He provided an example demonstrating how specific text can be bound to enum members. Consequently, we have agreed to use the following query string:
- `?includeComponents=person-name`: Name components will be populated
- `?includeComponents=none`: Bad request
- `?includeComponents=anything-else-else`: bad request

2024-09-23 12:42 UTC, SandGrainOne commented on src/Altinn.Register/src/Altinn.Register/Clients/PartiesClient.cs
> +            _memoryCache.Set(cacheKey, partyName, new TimeSpan(0, _cacheTimeoutForPartyNames, 0));
We're making the assumption that we will continue to always include name components regadless of input parameter. This will change in the future.

2024-09-23 15:18 UTC, Alxandr commented on src/Altinn.Register/src/Altinn.Register/Clients/PartiesClient.cs
> +            _memoryCache.Set(cacheKey, partyName, new TimeSpan(0, _cacheTimeoutForPartyNames, 0));
This code is just the A2 bridge implementation. It will all be changed once we go against the A3 register db.

2024-09-24 11:27 UTC, Ahmed-Ghanam commented on src/Altinn.Register/test/Altinn.Register.Tests/IntegrationTests/PartiesControllerTests.cs
> +    public async Task PostPartyNamesLookup_ValidInput_NameComponents_OK(string[] socialSecurityNumber, PartyComponentOptions nameComponent)
These use cases have been implemented and discussed in another comment. Closing this one.

2024-09-24 12:54 UTC, Alxandr approved these changes

2024-09-24 12:54 UTC, Alxandr commented on src/Altinn.Platform.Models/src/Altinn.Platform.Models/Register/PartyComponentOption.cs
> +public enum PartyComponentOption : uint
`Flags` enums should be named plurally, `PartyComponentOptions`.

2024-09-24 12:54 UTC, Alxandr commented on src/Altinn.Register/src/Altinn.Register.Core/Parties/IV1PartyService.cs
> +    IAsyncEnumerable<PartyName> LookupPartyNames(IEnumerable<PartyLookup> lookupValues, PartyComponentOption partyComponentOption, CancellationToken cancellationToken = default);
Please keep the `V1Models` - there is a reason it was introduced here as preparation for V2 models.

2024-09-24 12:54 UTC, Alxandr commented on src/Altinn.Register/src/Altinn.Register/ApiDescriptions/AccessListIncludesSchemaFilter.cs
> +public sealed class AccessListIncludesSchemaFilter
```suggestion
public sealed class PartyComponentOptionSchemaFilter
```

2024-09-24 12:54 UTC, Alxandr commented on src/Altinn.Register/test/Altinn.Register.Tests/IntegrationTests/PartiesControllerTests.cs
> +            { ["01039012345","01017512345"], null },
You can remove `null` here as it's identical to `string.Empty` since it's only used to build up a query-string.

2024-09-25 06:37 UTC, merged